import json, os, shutil, sys

sys.stdout = open(sys.stdout.fileno(), mode='w', encoding='utf-8', buffering=1)

with open('C:/Web-haven/gloomhaven/src/data/abilities.json', 'r', encoding='utf-8') as f:
    data = json.load(f)

base = 'D:/Download/Gloom/Katry'
dest_base = 'C:/Web-haven/gloomhaven/public/img/abilities'

# CZ photo name -> EN ability ID, per class
# refClassId mapping
ref_map = {
    'berserker': 'BE', 'beast_tyrant': 'BT', 'mindthief': 'MT',
    'summoner': 'SU', 'nightshroud': 'NS', 'spellweaver': 'SW',
    'doomstalker': 'DS', 'sunkeeper': 'SK', 'quartermaster': 'QM',
    'elementalist': 'EL', 'sawbones': 'SB', 'soothsinger': 'SS',
    'plagueherald': 'PH', 'diviner': 'DR',
}

folder_map = {
    'berserker': 'Inoxská fúrie',
    'beast_tyrant': 'Krysácký zvěropán',
    'mindthief': 'Krysácká zlodějka mysli',
    'summoner': 'Aestherská vyvolávačka',
    'nightshroud': 'Aestherský stínochodec',
    'spellweaver': 'Orchidská čarovnice',
    'doomstalker': 'Orchidský zkázolov',
    'sunkeeper': 'Valrathská světlonoška',
    'quartermaster': 'Valrathský zbrojmistr',
    'elementalist': 'Savvasská vládkyně živlů',
    'sawbones': 'Lidský kostiřez',
    'soothsinger': 'Quatrylská čaropěvkyně',
    'plagueherald': 'Trýznitelský moronoš',
    'diviner': 'Věštkyně',
}

mappings = {
    'berserker': {
        "nespoutana_sila": "unbridled-power",
        "utlumeni_bolesti": "numb-the-pain",
        "sklenene_kladivo": "glass-hammer",
        "odhodlany_postoj": "resolute-stand",
        "odrazeni": "bounce-back",
        "vybuch_hnevu": "growing-rage",
        "zuriva_pomoc": "furious-aid",
        "sila_agonie": "strength-in-agony",
        "vypaleni_rany": "cauterize",
        "zmrtvychvstani": "from-the-brink",
        "omracujici_zraneni": "dazing-wound",
        "smrti_navzdory": "defiance-of-death",
        "krvava_umluva": "blood-pact",
        "bezhlavy_najezd": "careless-charge",
        "utrzena_ze_retezu": "break-the-chains",
        "smrtici_zurivost": "fatal-fury",
        "ostnata_zbroj": "spiked-armor",
        "blyskave_rozptyleni": "shiny-distraction",
        "vir_seker": "flurry-of-axes",
        "rudy_zavoj": "seeing-red",
        "posledni_boj": "final-fight",
        "rohy_demona": "devil-horns",
        "nezastavitelna_zkaza": "unstoppable-destruction",
        "neopatrny_vypad": "reckless-offensive",
        "spalujici_nenavist": "burning-hatred",
        "mstivy_napor": "vengeful-barrage",
        "kostilam": "bone-breaker",
        "nesmrtelnost": "immortality",
        "hrdlo_silenstvi": "the-maw-of-madness",
    },
    'beast_tyrant': {
        "povzbuzujici_uder": "energizing-strike",
        "trny_skal": "earthen-spikes",
        "kruty_spojenec": "vicious-ally",
        "nezastavitelna_bestie": "unstoppable-beast",
        "prulom": "punch-through",
        "prastary_ochrance": "ancient-ward",
        "zbesilost": "rampage",
        "symbol_kamene": "stone-sigil",
        "hlad_po_krvi": "blood-hunger",
        "prvotni_pozehnani": "primal-blessing",
        "symbol_vichru": "storm-sigil",
        "moc_bice": "tyrannical-force",
        "ostry_vypad": "lash-out",
        "prirodni_prostredky": "natural-remedy",
        "celisti_smrti": "jaws-of-death",
        "symbol_klanu": "tribal-sigil",
        "soustredena_agrese": "focused-aggression",
        "plachtici_spojenec": "soaring-ally",
        "zapujcena_podstata": "borrowed-essence",
        "mocny_vypad": "forceful-swipe",
        "jedovaty_spojenec": "venomous-ally",
        "neunavny_spojenec": "relentless-ally",
        "trhac": "maul",
        "kvilejici_strely": "howling-bolts",
        "zelezna_srst": "patch-fur",
        "vymena_dusi": "spirit-swap",
        "matouci_rev": "disorienting-roar",
        "mizejici_zraneni": "disappearing-wounds",
        "soustredeny_hnev": "concentrated-rage",
    },
    'mindthief': {
        "cizopasny_vliv": "parasitic-influence",
        "hryzava_horda": "gnawing-horde",
        "podrizene_postaveni": "submissive-affliction",
        "vstric_noci": "into-the-night",
        "slabina_v_mysli": "the-minds-weakness",
        "strasiva_cepel": "fearsome-blade",
        "zamotana_smycka": "feedback-loop",
        "napor_empatie": "empathetic-assault",
        "zvracene_ostri": "perverse-edge",
        "mihnuti": "scurry",
        "spinavy_drap": "withering-claw",
        "posednuti": "possession",
        "mrazive_zjeveni": "frigid-apparition",
        "zalostna_stvura": "wretched-creature",
        "nepratelske_prevzeti": "hostile-takeover",
        "mozkova_pijavice": "brain-leech",
        "tichy_vykrik": "silent-scream",
        "kleptomanka": "pilfer",
        "lebecni_pretizeni": "cranium-overload",
        "zmrazeni_mysli": "frozen-mind",
        "masova_hysterie": "mass-hysteria",
        "temna_zbesilost": "dark-frenzy",
        "objeti_zkazenosti": "corrupting-embrace",
        "kruta_krev": "vicious-blood",
        "psychicka_projekce": "psychic-projection",
        "nadvlada": "domination",
        "spolecna_nocni_mura": "shared-nightmare",
        "mnoho_bude_jednim": "many-as-one",
        "vrazedny_prelud": "phantasmal-killer",
    },
    'summoner': {
        "neuprosna_hybnost": "inexorable-momentum",
        "nekoncici_nadvlada": "unending-dominance",
        "mocne_pouto": "mighty-bond",
        "hlineny_or": "earthen-steed",
        "zivouci_noc": "living-night",
        "sila_v_poctu": "strength-in-numbers",
        "oziveni_divociny": "wild-animation",
        "rozdelena_mysl": "divided-mind",
        "koznata_kridla": "leathery-wings",
        "zivouci_hora": "living-mountain",
        "kousavy_vitr": "biting-wind",
        "etericke_slahouny": "ethereal-vines",
        "privolana_pomoc": "conjured-aid",
        "spoutana_sila": "bonded-might",
        "tekavy_plamen": "volatile-flame",
        "ukovana_zurivost": "forged-ferocity",
        "uchopeni_prazdnoty": "grasping-the-void",
        "roztrzeni_zavoje": "tear-the-fabric",
        "slizke_zjeveni": "oozing-manifestation",
        "neochvejna_paze": "unwavering-hand",
        "nekonecno_hrotu": "endless-spikes",
        "negativni_energie": "negative-energy",
        "hul_vizi": "staff-of-visions",
        "matouci_zjeveni": "intervening-apparitions",
        "hnev_z_jineho_sveta": "otherworldly-rage",
        "pani_sfer": "black-fire",
        "rohane_velicenstvo": "horned-majesty",
    },
    'nightshroud': {
        "hlas_noci": "voice-of-the-night",
        "vycerpavajici_zraneni": "enervating-wound",
        "posilujici_prazdnota": "empowering-void",
        "skryta_vyhoda": "hidden-advantage",
        "plast_stinu": "cloak-of-shadows",
        "na_kridlech_noci": "smoke-step",
        "ticha_sila": "silent-force",
        "tanec_stinu": "shadow-dance",
        "duch_noci": "spirit-of-the-night",
        "cerne_noze": "black-knives",
        "cihajici_zkaza": "lurking-ruin",
        "priprava_na_vrazdu": "prepare-for-the-kill",
        "ticha_zbesilost": "open-frenzy",
        "oci_noci": "eyes-of-the-night",
        "spary_noci": "midnight-claws",
        "cepel_hruzy": "terror-blade",
        "plamen_duse": "soul-flame",
        "temny_oblak": "dark-cloud",
        "andel_smrti": "angel-of-death",
        "cerny_sip": "black-arrow",
        "nevideny_des": "unseen-dread",
        "ponura_vyziva": "grim-sustenance",
        "chmurna_sipka": "drain-vitality",
        "soumrak": "dawn-of-twilight",
        "pozreny_strachem": "consumed-by-fear",
        "proklety_vanek": "cursed-breeze",
        "zbroj_noci": "night-armor",
        "tichy_jako_kour": "quiet-as-smoke",
    },
    'spellweaver': {
        "ledovy_uder": "icy-blast",
        "blyskavy_vybuch": "flashing-burst",
        "pomoc_zivlu": "aid-from-the-ether",
        "plameny_mrazu": "frozen-night",
        "duch_zkazy": "spirit-of-doom",
        "rozvetveny_paprsek": "forked-beam",
        "exploze_barev": "chromatic-explosion",
        "plast_z_plamenu": "engulfed-in-flames",
        "mraziva_noc": "cold-front",
        "zivouci_pochoden": "living-torch",
        "kamenne_pesti": "stone-fists",
        "dvojita_obnova": "twin-restoration",
        "kridla_zefyru": "zephyr-wings",
        "studena_fronta": "frost-armor",
        "cerna_dira": "black-hole",
        "ohnive_peklo": "fire-orbs",
        "probuzeni_car": "reviving-ether",
        "carovra_pomoc": "mystic-ally",
        "carovny_vyboj": "arcane-flurry",
        "ohnive_koule": "volatile-exploding",
        "tvrzene_hroty": "hardened-spikes",
        "plamenny_uder": "flame-strike",
        "mraziva_zbroj": "freezing-nova",
        "na_kridlech_vetru": "ride-the-wind",
        "mrazivy_vybuch": "impaling-eruption",
        "praskajici_vyboje": "crackling-air",
        "bodavy_vybuch": "wrath-of-the-elements",
    },
    'doomstalker': {
        "slabe_misto": "vulnerable-spot",
        "neuprosny_napor": "press-the-attack",
        "potemnela_obloha": "darkened-skies",
        "zesileni_utoku": "harrowing-assault",
        "ostnata_past": "stinging-cloud",
        "pevne_soustredeni": "steady-focus",
        "zurivy_rozkaz": "swift-command",
        "nezvratny_osud": "undeniable-fate",
        "maskovani": "camouflage",
        "divocina_hladovi": "deathly-swarm",
        "konec_se_blizi": "doom-approaches",
        "drtiva_vlna": "apocalyptic-blast",
        "nakazlive_zatraceni": "contagious-blight",
        "instinkty_selmy": "beast-instincts",
        "jatka": "slaughter",
        "lovec_a_korist": "hunter-and-prey",
        "rychly_trik": "quick-trickery",
        "naslapna_mina": "lead-astray",
        "dest_sipu": "rain-of-arrows",
        "chvile_oddechu": "moment-of-rest",
        "rychly_toulec": "quick-quiver",
        "pevny_luk": "steady-bow",
        "spech_do_hrobu": "rush-of-death",
        "certstve_maso": "fresh-kill",
        "stremhlavy_utok": "bite-the-hand",
        "desiva_kletba": "frightening-curse",
        "ostre_klektaky": "sharpened-talons",
        "mrzacici_smycka": "crippling-noose",
        "pytlacke_oko": "poachers-eye",
        "vysavani_zivota": "life-siphon",
        "lov_zacina": "the-hunt-begins",
    },
    'sunkeeper': {
        "spravedliva_sila": "righteous-strength",
        "takticky_rozkaz": "tactical-order",
        "neochvejna_duvera": "unwavering-mandate",
        "spalujici_zablesk": "burning-flash",
        "zarici_hav": "engulfing-radiance",
        "cesta_slavy": "path-of-glory",
        "oslneni": "radiant-command",
        "jasna_zastita": "searing-shield",
        "inspirujici_svatost": "inspiring-sanctity",
        "pomoc_shury": "aid-from-above",
        "vahy_spravedlnosti": "scales-of-justice",
        "uder_kladiva": "hammer-blow",
        "zbran_cistoty": "weapon-of-purity",
        "oslnivy_vypad": "dazzling-charge",
        "sila_ocisty": "purifying-aura",
        "povzneseni_na_nebesa": "ascension",
        "usvit": "daybreak",
        "mobilizujici_postulat": "mobilizing-axiom",
        "prakticke_plany": "practical-plans",
        "obranny_postoj": "defensive-stance",
        "svaty_choral": "supportive-chant",
        "opatrny_postup": "cautious-advance",
        "povzbuzujici_rozkaz": "rallying-command",
        "lecive_ruce": "healing-hands",
        "velkolepy_vyboj": "glorious-bolt",
        "zarici_modlitba": "radiant-prayer",
        "ochranne_pozehnani": "protective-blessing",
        "ocistujici_aura": "cleansing-aura",
        "majak_svetla": "beacon-of-light",
        "svaty_uder": "holy-strike",
    },
    'quartermaster': {
        "pytel_cennosti": "bag-of-holding",
        "svitek_smrti": "trail-of-destruction",
        "prenosna_balista": "deployed-ballista",
        "opevnene_postaveni": "fortified-position",
        "vitane_osvezeni": "refreshing-break",
        "svitek_blizardu": "scroll-of-blizzard",
        "zkazonosna_vybusina": "catastrophic-bomb",
        "toulec_plny_sipu": "quiver-of-arrows",
        "kalena_ocel": "tempered-steel",
        "svitek_rozsudku": "scroll-of-judgement",
        "obruv_kyj": "giant-club",
        "drobny_vacek": "small-pouch",
        "svitek_blesku": "scroll-of-lightning",
        "pravidelne_dodavky": "restock",
        "naostreny_bumerang": "bladed-boomerang",
        "znovuzkuti": "reforge",
        "zrychleny_pochod": "forced-march",
        "velky_vak": "oversized-pack",
        "nabodnuti_na_kopi": "spike-trap",
        "zmrzaceni_sipem": "crippling-bow",
        "rozseknutí_sekerou": "cleaving-axe",
        "sada_brousku": "sharpening-kit",
        "dozasobeni": "hastened-step",
        "zelezna_zed": "iron-bulwark",
        "zbehlost": "proficiency",
        "svitek_navraceni": "scroll-of-recall",
        "odlozena_energie": "stored-energy",
        "rozdrceni_kladivem": "crushing-hammer",
    },
    'elementalist': {
        "zjeveni_zivlu": "elemental-manifestation",
        "rovnovaha_zivlu": "elemental-balance",
        "stit_zivlu": "elemental-aegis",
        "tekavy_zivel": "volatile-element",
        "nezbytne_posileni": "necessary-boost",
        "pomsta": "retribution",
        "oko_boure": "the-eye-of-the-storm",
        "napodobeni": "mimic",
        "ulomky_obsidianu": "obsidian-shards",
        "ostri_zimy": "winters-edge",
        "sterkove_tornado": "gravel-vortex",
        "kouzlo_protikladu": "opposing-elements",
        "retezovy_blesk": "chain-lightning",
        "pohrbeni_zaziva": "buried-alive",
        "mraziva_exploze": "frozen-explosion",
        "vrouci_proud": "boiling-arc",
        "ledove_trny": "ice-spikes",
        "tvarovani_hmoty": "malleable-elements",
        "ohnivy_vir": "fire-whirl",
        "mrazivy_paprsek": "ray-of-frost",
        "surove_zivly": "raw-elements",
        "erupce_lavy": "lava-eruption",
        "cire_zivly": "pure-elementalism",
        "beztvara_sila": "formless-power",
        "virici_cyklon": "whirling-cyclone",
        "krupobitI": "hail",
        "tvarne_zivly": "stunning-blast",
        "stinovy_zavoj": "shadow-veil",
        "jasny_zablesk": "brilliant-flash",
    },
    'sawbones': {
        "hrozivy_uraz": "tending-the-wound",
        "prvni_pomoc": "first-aid",
        "lekarsky_recept": "prescription",
        "rychla_pomoc": "quick-aid",
        "vakcina": "vaccination",
        "krevni_transfuze": "blood-transfusion",
        "jista_ruka_chirurgova": "hand-of-the-surgeon",
        "nepodcenujte_prevenci": "prevention-is-key",
        "regenerace_tkani": "tissue-regeneration",
        "skrtidlo": "tourniquet",
        "zadrzet_bolest": "hold-back-the-pain",
        "chirurgicka_brasna": "syringe-kit",
        "vyzkum_leku": "research-the-cure",
        "hnev_gentlemana": "gentlemans-anger",
        "lecivy_balicek": "medical-pack",
        "zkrvavena_pila": "bloody-saw",
        "predoperacni_priprava": "precaution",
        "mistrovsky_lecitel": "master-physician",
        "eutanazie": "euthanize",
        "amputace": "amputate",
        "poruseni_prisahy": "do-no-harm",
        "nezbytny_uder": "necessary-strike",
        "predbezne_opatreni": "ounce-of-prevention",
        "pece_o_nemocne": "medical-supplies",
        "diagnoza": "diagnosis",
        "tymova_prace": "team-effort",
        "leciva_smes": "cobbled-together",
        "jehla": "needle",
        "posilujici_injekce": "booster-shot",
        "polni_medicina": "field-medicine",
        "velky_lecivy_balicek": "large-healing-kit",
    },
    'soothsinger': {
        "matouci_zalozpev": "disorienting-dirge",
        "arie_ozven": "echoing-aria",
        "inspirujici_hymna": "inspiring-hymn",
        "takt_mobilizace": "mobilizing-measure",
        "zabrnkat_na_struny": "pull-the-strings",
        "serenada_z_nocni_mury": "nightmare-serenade",
        "dunivy_proklamace": "imposing-command",
        "panovacna_pritomnost": "dominating-presence",
        "podmanivy_predstaveni": "captivating-performance",
        "pokojny_trylek": "perplexing-puzzle",
        "zmena_rytmu": "change-tempo",
        "desuplna_reakce": "frightful-reaction",
        "stinove_loutky": "shadow-puppets",
        "zpivajici_sip": "singing-arrow",
        "ladeni_dopadu": "tuning-the-outcome",
        "vrzeny_hlas": "ventriloquism",
        "melodie_v_harmonii": "harmonized-melody",
        "hbity_nuz": "nimble-knife",
        "mrzacici_chor": "crippling-chorus",
        "uklidnujici_ukolebavka": "soothing-lullaby",
        "zraneni_tesklivosti": "wound-of-woe",
        "pisen_rychlosti": "song-of-speed",
        "volani_do_zbrane": "call-to-arms",
        "mocna_balada": "hurried-blade",
        "nekonecny_napev": "unending-chant",
        "pochodovy_rytmus": "marching-beat",
        "dyka_na_ochranu": "protective-blade",
        "obranny_popevek": "defensive-ditty",
    },
    'plagueherald': {
        "shromazdeni_zkazy": "gathering-doom",
        "okridleny_sbor": "winged-congregation",
        "pachnouci_vichr": "foul-wind",
        "urychleny_konec": "accelerated-end",
        "plynny_jed": "vile-pestilence",
        "hromadne_vymirani": "mass-extinction",
        "nepredstavitelne_utrpeni": "unthinkable-torment",
        "hnilobni_cervi": "writhing-worms",
        "temny_priliv": "dark-tide",
        "sirici_se_pohroma": "spreading-scourge",
        "odporna_nakaza": "repulsive-infection",
        "moc_nakazy": "plague-of-power",
        "temna_umluva": "dark-covenant",
        "pod_kuzi": "under-the-skin",
        "poddej_se_daru": "succumb-to-the-gift",
        "boure_kridel": "storm-of-wings",
        "dobrovolna_obet": "resigned-sacrifice",
        "mrak_zihadel": "cloud-of-stingers",
        "zhoubna_kletba": "carrier-swarm",
        "bidny_roj": "swarm-of-misery",
        "nakazliva_choroba": "contagion",
        "epidemie": "epidemic",
        "vir_puchyru": "blistering-vortex",
        "rozptyleny_des": "scattered-terror",
        "paralyzujici_kousnuti": "paralyzing-bite",
        "stipajici_komari": "biting-gnats",
        "pliziva_kletba": "creeping-curse",
        "svirajici_havet": "stinging-cloud",
        "zkazeny_vitr": "corrupted-wind",
    },
}

# Copy photos and update abilities with CZ names
copied = 0
errors = []
cz_names_added = 0

for cls, mapping in mappings.items():
    ref = ref_map[cls]
    folder = folder_map[cls]
    src_dir = os.path.join(base, folder)
    dst_dir = os.path.join(dest_base, ref)
    os.makedirs(dst_dir, exist_ok=True)

    for cz_name, en_id in mapping.items():
        src = os.path.join(src_dir, cz_name + '.jpg')
        dst = os.path.join(dst_dir, en_id + '.jpg')
        if os.path.exists(src):
            shutil.copy2(src, dst)
            copied += 1
        else:
            errors.append(f'Missing: {src}')

    # Add CZ names to abilities.json
    # Build reverse: en_id -> cz display name
    reverse = {}
    for cz_file, en_id in mapping.items():
        # Convert filename to display name: replace _ with space, capitalize
        display = cz_file.replace('_', ' ').capitalize()
        # Capitalize first letter of each sentence
        reverse[en_id] = display

    for ability in data:
        if ability['classId'] == cls and ability['id'] in reverse:
            ability['nameCz'] = reverse[ability['id']]
            cz_names_added += 1

with open('C:/Web-haven/gloomhaven/src/data/abilities.json', 'w', encoding='utf-8') as f:
    json.dump(data, f, indent=2, ensure_ascii=False)

print(f'Copied {copied} photos')
print(f'Added {cz_names_added} CZ names to abilities.json')
if errors:
    print(f'Errors ({len(errors)}):')
    for e in errors:
        print(f'  {e}')
